### ISSUE TITLE
Problem writing Eleventy Templates : unexpected token ")"

### ISSUE THREAD

**Issue by yazae** [web-alchemy/eleventy-plugin-content-dates#5]
Hi !

I’m trying to use the eleventy "Last Modified" date for my edit field in the frontmatter, but it doesn’t work (I’m probably mistaken somewhere but idk).

I found your plugin and tried it, but with my liquid template, it doesn’t seem to work :

```11ty
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "_site/logs/flux-rss-and-digital-garden/index.html" from "./logs/Flux RSS & Digital Garden.md" (via EleventyTemplateError)
[11ty] 2. unexpected token ")", value expected, file:./layouts/log.md, line:9, col:48 (via TokenizationError)
[11ty]
[11ty] Original error stack trace: unexpected token ")", value expected, file:./layouts/log.md, line:9, col:48
[11ty]     7|     {%- else -%}
[11ty]     8|       Log publié le {{ page.date | date: "%d-%m-%Y" }}.
[11ty] >>  9|       Éditée le {{ updatedAt.toLocaleDateStrin() }}.
[11ty]                                                       ^
```

my log.md file :

```liquid
    {%- if lang == "en" -%}
      Log published the {{ page.date | date: "%d-%m-%Y" }}.
      Edited the {{ edit | date: "%d-%m-%Y" }}.
    {%- else -%}
      Log publié le {{ page.date | date: "%d-%m-%Y" }}.
      Éditée le {{ updatedAt.toLocaleDateString() }}.
    {%- endif -%}
```

the front matter of the note :

```YAML
---
title: Flux RSS & Digital Garden
aliases: 
date: 2024-06-22
updatedAt: 2024-06-22
logtype: feed
tags:
  - Meta
  - Tech
  - Draft
description: Réflexions sur les flux RSS appliqués à un Digital Garden
---
```

Do you have any idea why it doesn’t work ? Does your plugin support liquid ?
Usually, in liquid, we use filters, and it doesn’t use a js function 🤔 

Sorry if my question is a noob question, I’m not very knowledgeable in js and english isn’t my first language so there can be comprehension errors ^^

Thanks for your work anyways !
